# Generated by Django 5.2.6 on 2025-09-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_video_feed_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdb',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
