# Generated by Django 5.2.6 on 2025-10-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_video_feed_app', '0003_userinput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInput',
        ),
        migrations.RenameField(
            model_name='contentdb',
            old_name='image',
            new_name='generated_image',
        ),
        migrations.RenameField(
            model_name='contentdb',
            old_name='video',
            new_name='generated_video',
        ),
        migrations.AddField(
            model_name='contentdb',
            name='uploaded_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
