# Generated by Django 5.2.6 on 2025-10-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_video_feed_app', '0005_oauthtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentdb',
            name='uploaded_image',
        ),
        migrations.AddField(
            model_name='contentdb',
            name='fb_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contentdb',
            name='ig_post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contentdb',
            name='posted_to_fb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentdb',
            name='posted_to_ig',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WeeklySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('media_type', models.CharField(max_length=10)),
                ('posted_fb', models.BooleanField(default=False)),
                ('posted_ig', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_video_feed_app.contentdb')),
            ],
        ),
    ]
