# Generated by Django 5.2.6 on 2025-10-14 05:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_video_feed_app', '0007_metapage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetaPage',
            new_name='MetaPageDB',
        ),
    ]
