# Generated by Django 5.2.6 on 2025-10-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_video_feed_app', '0008_rename_metapage_metapagedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdb',
            name='uploaded_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
